import AdminPage from "@/src/components/admin/AdminPage";
import LeadInbox from "@/src/components/admin/LeadInbox";
import { adminBackendJson } from "@/src/lib/admin-backend";

type OrderRequest = {
  id: string;
  name: string;
  email: string;
  phone?: string | null;
  notes?: string | null;
  status: "NEW" | "REVIEWED" | "CONTACTED" | "CLOSED";
  items: Array<{ product?: { title?: string } }>;
};

type NewsletterSubscription = {
  id: string;
  email: string;
  source?: string | null;
  status?: string;
  subscribedAt?: string;
};

type ProgramReservation = {
  id: string;
  name: string;
  email: string;
  phone?: string | null;
  notes?: string | null;
  status: "NEW" | "REVIEWED" | "CONTACTED" | "CLOSED";
  program: { name: string };
};

type RetreatInquiry = {
  id: string;
  name: string;
  email: string;
  phone?: string | null;
  notes?: string | null;
  status: "NEW" | "REVIEWED" | "CONTACTED" | "CLOSED";
  retreat: { name: string };
};

type ProductNotification = {
  id: string;
  email: string;
  source?: string | null;
  status: "NEW" | "REVIEWED" | "CONTACTED" | "CLOSED";
  createdAt?: string;
  product?: { title?: string; slug?: string; status?: string } | null;
};

export default async function LeadsPage() {
  const [orders, newsletter, programs, retreats, notifications] = await Promise.all([
    adminBackendJson<{ items: OrderRequest[] }>("/lead/order-requests"),
    adminBackendJson<{ items: NewsletterSubscription[] }>("/lead/newsletter-subscriptions"),
    adminBackendJson<{ items: ProgramReservation[] }>("/lead/program-reservations"),
    adminBackendJson<{ items: RetreatInquiry[] }>("/lead/retreat-inquiries"),
    adminBackendJson<{ items: ProductNotification[] }>("/lead/product-notifications"),
  ]);

  return (
    <AdminPage
      title="Lead Inbox"
      description="Review, contact, and close the incoming requests generated by checkout, newsletter, program, retreat, and Notify Me flows."
    >
      <LeadInbox
        orderRequests={orders.items}
        newsletterSubscriptions={newsletter.items}
        programReservations={programs.items}
        retreatInquiries={retreats.items}
        productNotifications={notifications.items}
      />
    </AdminPage>
  );
}
